cholla-hydro/cholla

python_scripts/README.md
I offer some notes I wrote for myself when trying out the visualization and basic data manipulation scripts.
=> Add README for visualization scripts.

.gitignore, Makefile, README.md, aomake-paris-hipfft.sh, aomake-paris-pfft.sh, aomake-paris.sh, aorun-paris-hipfft.sh, aorun-paris-pfft.sh, aorun-paris.sh
Fixed the Makefile. Removed `Makefile` from `.gitignore` because the build scripts rely on it. Updated the README to document the build and run scripts. Fixed the `ao` scripts so they don't rely on my login environment.
=> Fixed Makefile. Updated README.

src/io.cpp
Hi Evan, this was the change to allow temperature to be outputted when not running with the dual energy flag.
=> Output temp in projection

Makefile, builds/check.sh, builds/machine.sh, builds/make.host.poplar, builds/make.host.poplar.aomp, builds/make.host.poplar.cce+hip, builds/scripts/amake-paris-pfft.sh, builds/scripts/nmake-paris-cufft.sh, builds/scripts/nmake-paris-pfft.sh, builds/scripts/nmake-paris.sh, builds/setup.poplar.aomp.sh, builds/setup.poplar.cce+hip.sh, python_scripts/numdiff.py
This PR contains python script `numdiff.py` to compare files numerically for regression testing and other minor modifications in Makefile and build-related scripts for Poplar compilers.
=> Numdiff and Makefile mods

builds/machine.sh, builds/make.host.crc, builds/prereq.sh, builds/scripts/crc-make-sor.sh
changes to support building on CRC (power9)
=> build on crc (power9)

.gitignore, Makefile, builds/prereq.sh, builds/scripts/amake-paris-sor.sh, builds/scripts/amake-sor.sh, builds/scripts/aomake-paris-pfft.sh, builds/scripts/aomake-paris-sor.sh, builds/scripts/aomake-sor.sh, builds/scripts/nmake-paris-sor.sh, builds/scripts/nmake-sor.sh, src/gpu.hpp, src/gravity/grav3D.cpp, src/gravity/gravity_boundaries.cpp, src/gravity/gravity_functions.cpp, src/gravity/paris/PoissonPeriodic3DBlockedGPU.cu, src/gravity/paris/PoissonZero3DBlockedGPU.cu, src/gravity/paris/PoissonZero3DBlockedGPU.hpp, src/gravity/potential_SOR_3D.cpp, src/gravity/potential_SOR_3D_gpu.cu, src/gravity/potential_paris_3D.cu, src/gravity/potential_paris_3D.h, tests/scripts/aorun-paris-pfft.sh, tests/scripts/aorun-paris-sor.sh, tests/scripts/aorun-sor.sh, tests/scripts/arun-paris-sor.sh, tests/scripts/arun-paris-sphere.sh, tests/scripts/arun-sor.sh, tests/scripts/nrun-paris-sor.sh, tests/scripts/nrun-sor.sh, tests/scripts/sphere.txt
Updated build and runs scripts. Fixed bugs in spherical boundary conditions. Added analytic test of SOR and Paris solvers with nonzero-boundary conditions. Added comparison of SOR and Paris results with exact spherical result. Converted to using `M_PI` standard value.
=> Support for nonzero boundary conditions with Paris Poisson solver.

Makefile, builds/scripts/smake-paris-cufft.sh, builds/scripts/smake-paris-sor.sh, builds/scripts/smake-regression.sh, src/gpu.hpp, src/gravity/paris/PoissonPeriodic3x1DBlockedGPU.cu, tests/scripts/srun-paris-sor.sh
Updates for Summit build and run scripts. Small code fixes for Summit.
=> Summit updates

src/particles/particles_boundaries_cpu.cpp
=> simple bugfix for particles transfers

builds/setup.spock.cce.sh, src/gravity/gravity_boundaries_gpu.cu, src/particles/particles_boundaries.cpp
Synchronizations needed for GPU buffer packing kernels for cosmology test run on Spock to reproduce Summit's.
=> Synchronizations for GPU Buffer Packing

src/system_tests/hydro_system_tests.cpp, src/system_tests/input_files/tHYDROSYSTEMConstant_CorrectInputExpectCorrectOutput.txt, src/system_tests/input_files/tHYDROSYSTEMSoundWave3D_CorrectInputExpectCorrectOutput.txt, src/system_tests/system_tester.cpp, src/system_tests/system_tester.h, src/utils/testing_utilities.cpp, src/utils/testing_utilities.h
Also demonstrates an example of running analytic tests in hydro_system_tests.cpp,
adds a few helper functions,
and makes _loadTestFieldData public.
=> add constant and sound 3D test

src/gravity/grav3D.cpp, src/gravity/grav3D.h, src/gravity/gravity_functions.cpp, src/grid/grid3D.cpp, src/grid/grid3D.h, src/grid/initial_conditions.cpp, src/io/io.cpp, src/main.cpp, src/mpi/mpi_routines.cpp, src/mpi/mpi_routines.h, src/particles/feedback_CIC.cpp, src/particles/particles_3D.cpp, src/particles/particles_boundaries.cpp
- Improved Get_Position so that multi-GPU and single-GPU match perfectly for Rayleigh_Taylor problem (and generally, anything that relies on Get_Position returning the exact same position for the same cell whether it's single-GPU or multi-GPU). 
- Remove Set_Parallel_Domain, move functionality into src/grid/initial_conditions.cpp @@ Grid3D::Set_Domain_Properties
- Remove domlen_x/y/z
- Particles x/y/zMax inherits from Grav
- Grav x/y/zMax inherits from Grid
- This way, all domain xMin and xMax are being controlled by Grid3D::Set_Domain_Properties. 
The key motivation for this rework is that the distributive law does not hold for floating point operations. That is:
```a + (b1 + b2) * c != a + b1*c + b2*c. ```
[Here is a demo!](https://tio.run/##Sy4o0E1PTv7/PzOvRCE3MTNPQ7OaS4FLISW/NCknVSGlQs …
=> Caar domain

src/system_tests/gravity_system_tests.cpp, src/system_tests/input_files/tGRAVITYSYSTEMSphericalCollapse_CorrectInputExpectCorrectOutput.txt
This commit adds a spherical collapse system test designed to test the gravity + hydro build.
=> Gravity system test

.github/workflows/build_tests.yml
=> new build-tests.yml for Docker container

src/grid/initial_conditions.cpp
Gravity system test now passes.
=> Reset spherical overdensity ICs to old values. 

builds/run_tests.sh, src/riemann_solvers/hlld_cuda.cu, src/riemann_solvers/hlld_cuda.h, src/riemann_solvers/hlld_cuda_tests.cu, src/utils/mhd_utilities.h
This makes passing all the variables around much simplier, makes the solver much more readable, and enables us to put pretty much everything into testable functions.
=> Refactor HLLD solver with structs

src/riemann_solvers/hlld_cuda_tests.cu, src/utils/error_handling.cpp
- Fixed some logic bugs in `Check_Configuration`
- Fixed some HLLD internal tests passing on C-3PO but not on H2P when they should. Updating some data and loosening some restrictions did it.
=> Fix bugs in HLLD internal tests and `Check_Configuration` function

docs/doxygen/Doxyfile
Doxygen output gets a lot more interesting when all of the files are actually included by setting RECURSIVE = YES
=> Update Doxyfile for recursive search

examples/3D/orszag_tang_vortex.txt, src/grid/grid3D.h, src/grid/initial_conditions.cpp, src/system_tests/input_files/tMHDSYSTEMParameterizedMpi_OrszagTangVortexCorrectInputExpectCorrectOutput.txt, src/system_tests/mhd_system_tests.cpp
- Example parameter file in `examples/3D/orszag_tang_vortex.txt`
- New initial conditions type `Orszag_Tang_Vortex` and an initializing function of the same name
- New MHD system test for the Orszag-Tang vortex
=> Add Orszag-Tang vortex test & initial conditions

src/dust/dust_cuda.cu, src/dust/dust_cuda.h, src/dust/dust_cuda_tests.cpp
Mostly renamed variables and functions to conform with the naming that we decided on (described in [this discussion board](https://github.com/cholla-hydro/cholla/discussions/206)).
=> Update dust naming to conform with Cholla's naming conventions

src/io/io.cpp
This just fixes a bug that I introduced to ``chprintf``
=> minor bugfix related to chprintf

builds/make.host.lux, src/grid/boundary_conditions.cpp
Resolves issue #323.  
Added an if else statement so that the boundary conditions don't have to simultaneously satisfy noh and wind.
=> Allow Noh boundary conditions to be set on dev
