src/hydro_cuda.cu

On sparkle, compiling with
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
Gave the following compile error.
src/hydro_cuda.cu(661): error: calling a constexpr __host__ function("fmax") from a __global__ function("Calc_dt_3D") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
The function fmax() exists in math.h and cuda.h.  Because the constant "0" was being specified, I think the compiler interpreted this as an int and thought math:fmax() from the host was being called. A float must be provided to cuda:fmax(), so changing "0" to "0.0" fixed the problem.

Fixed type cast error in fmax() in hydro_cuda.cu

---

src/hllc_cuda.cu
src/roe_cuda.cu

Avoid uninitialized values for etah when H_CORRECTION if off.

Set etah=0 when H_CORRECTION is off on HLLC and ROE solvers 

---

src/CTU_3D_cuda.cu
src/VL_3D_cuda.cu
src/exact_cuda.cu
src/global.h
src/grid3D.h
src/hllc_cuda.cu
src/hydro_cuda.cu
src/hydro_cuda.h
src/initial_conditions.cpp
src/plmc_cuda.cu
src/plmp_cuda.cu
src/ppmc_cuda.cu
src/ppmp_cuda.cu
src/roe_cuda.cu
tests/3D/Spherical_Overpressure.txt

Pressure Calculation:
When using Dual Energy, each time the pressure is computed I apply condition from Bryan+2013 eq 44 to select the internal energy from which the pressure is computed. This was added to the following functions:
- All cuda reconstructions: PLMP, PLMC, PPMP and PPMC
- All cuda Riemann solvers: HLLC, ROE and EXACT
- When adding the term p_div(v) to the advected internal energy update. ( Not applied on the half step update when using VL, We decided not to add the p_div(V) term for the half update, but I didn't change the implementation here )
Internal Energy Synchronization:
Now, there are two steps for the Internal Energy Synchronization:
-First I select wich internal energy to keep by applying the condition from Bryan+2013 eq 45 and write the selected internal energy …

Dual energy fix

---

src/CTU_1D_cuda.cu
src/CTU_2D_cuda.cu
src/CTU_3D_cuda.cu
src/VL_1D_cuda.cu
src/VL_2D_cuda.cu
src/VL_3D_cuda.cu
src/cooling_wrapper.cu
src/grid3D.cpp

In my 3D experiments this resulted in about a 4x speedup for the simple
sod test, so I propagated the change to all host memory that ends up in
a call to hipMemCpy and friends.

Pin host memory for any data sent to/from device

---

.gitignore
makefile.template
python_scripts/README.md
python_scripts/cat_dset_3D.py
python_scripts/cat_projection.py
python_scripts/cat_rotated_projection.py
python_scripts/plot_sod.py
src/exact.cpp
src/global.h
src/grid3D.cpp
src/h_correction_3D_cuda.cu
src/hllc.cpp
src/main.cpp
src/plmc.cpp
src/plmc_cuda.cu
src/plmp_cuda.cu
src/ppmp_cuda.cu
src/roe.cpp
src/roe.h
tests/2D/disk.txt

Floating Point Number Precision
- NOTE: Single precision (32bit) floating point computations are
currently broken. That issue predates this commit but it was found
when testing this part of the commit.
- Make float precision choice cleaner
Prior to this change, the way the float precision was chosen was hard
to read and couldn't spawn an error message.
Now it takes 1/3rd as many lines, is much clearer, and has a clear
error message
Python Scripts
- Add platform agnostic shebangs to python scripts
- Make all python scripts executable
Makefile Tracking
- Move Makefile to makefile.template.
Prior to this change, the template makefile was just named `Makefile`
which could lead to unfortunate tracking issues when changing the
make or moving between systems. Now the template makefile is named …

Improve readability and conform to best practices

---

Makefile
README.md
src/gravity/paris/PoissonPeriodic3DBlockedGPU.cu

Paris itself still defaults to spectral accuracy, but it can be compiled with `-DPARIS_5PT` to solve for a 5-point numerical second derivative, or with `-DPARIS_3PT` to solve for a 3-point numerical second derivative.
The Makefile adds `-DPARIS_5PT` to the standard build with Paris. If the addition of `-DGRAVITY_5_POINTS_GRADIENT` is commented out of the Makefile, the build will switch to `-DPARIS_3PT`.
I ran a small test problem comparing Paris with PFFT, and it showed the following results.
Using `-DGRAVITY_5_POINTS_GRADIENT` but spectral accuracy for Paris:
```
Analytic Test of Poisson Solvers:
Paris Poisson-Solver Diff: L1 6.01283e-06 L2 5.03036e-06 Linf 5.6077e-06
PFFT Poisson-Solver Diff: L1 0.000959536 L2 0.0010211 Linf 0.00112875
Paris vs PFFT Poisson-Solver Diff: L1 5.40453e-05 …
```

Changed Paris solver to use a 5-point approximation of second derivatives

---

src/boundary_conditions.cpp
src/cuda_pack_buffers.cu
src/grid3D.h
src/initial_conditions.cpp
src/mpi_boundaries.cpp

- Fixed transmissive boundaries in boundary_conditions.cpp and cuda_pack_buffers.cu to avoid floating point errors by performing fewer FLOPs (output matches much better between HYDRO_GPU on/off). This is the most significant change in terms of output differences from previous versions of the code, but should be more accurate. (boundary_conditions.cpp and cuda_pack_buffers.cu)
- After more testing, I realized the CUDA version of the code requires thread synchronization as well, and previous tests somehow got lucky. (cuda_pack_buffers.cu)
- Cleanup of a lot of trash code I generated when making no_offload changes (mpi_boundaries.cpp)
- Enable HYDRO_GPU to be turned off while MPI_GPU is turned on (for hydro buffers, it will not use cuda-aware MPI) (mpi_boundaries.cpp)
- Refactor of …

Clean boundaries

---

src/global/global.cpp
src/global/global.h
src/main.cpp

This minor patch allows command line overrides, which is a quality-of-life convenience when testing and can reduce the # of input files needed to run a variety of tests. Use examples:
Changing the output directory 
`./bin/cholla tests/3D/constant.txt outdir=dir2/`
Changing the resolution
`./bin/cholla tests/3D/constant.txt nx=100 ny=100 nz=100`
Changing tout
`./bin/cholla tests/3D/constant.txt tout=1000.0 outstep=1000.0`
Changing parameters
`./bin/cholla tests/3D/constant.txt rho=1e2`
Everything combined
`./bin/cholla tests/3D/constant.txt outdir=dir2/ nx=100 ny=100 nz=100 tout=1000.0 rho=1e2`
Adding new params to the codebase should not be any different from before, as there is only one copy of the param parser, which is first used on the input file and then used on command line …

Command line override args

---

src/riemann_solvers/hllc_cuda_tests.cu
src/system_tests/hydro_system_tests.cpp
src/system_tests/particles_system_tests.cpp

The new test fixture enables the user to quickly write new tests for the
HLLC solver by moving almost all the boilerplate to the test fixture.
Now the user just needs to pass the `computeFluxes` method the left and
right states along with the adiabatic index. `computeFluxes` returns a
vector of the fluxes and then that vector can be passed to the
`checkResults` method, along with the fiducial values and (optionally)
a string for custom output, and that method will perform all the
assertions and I/O.
Added Doxygen comments to system tests and to the HLLC tests

Refactor HLLC test to use a test fixture and add doxygen comments to tests

---

src/global/global.h

`MAXLEN`'s previous value of 140 was leading to variables that were too small to hold path names. Increasing it to 2048 should  avoid this in most cases

Increase `MAXLEN` in global.h

---

builds/make.host.frontier
builds/scripts/run_tests.sh
src/system_tests/system_tester.cpp

- Added the GoogleTest path variable in `make.host.frontier`
- Added Crusher/Frontier to the list of hosts in `run_tests.sh`
- Fixed a bug the prevented GoogleTest from being built by
`buildAndRunTests` when the `-g` flag was passed to it
- Increased the absolute error allowed in systems tests. Previously it
was 1E-14 since that was an order of magnitude larger than the
differences between GCC and XL on NVIDIA hardware. AMD/Clang appear
to differ from NVIDIA/GCC/XL by roughly 1E-12 or approximately one
ten billionth of a percent

Add support for Crusher in testing

---

src/particles/particles_3D.cpp
src/particles/particles_3D.h
src/particles/particles_3D_gpu.cu
src/particles/particles_boundaries.cpp
src/particles/particles_boundaries_gpu.cu
src/utils/gpu_arrays_functions.cu
src/utils/gpu_arrays_functions.h

This pull request addresses issues encountered when the number of particles in a given GPU exceeds the size of the arrays and transfer buffers initially allocated.
When transferring the particles via MPI, before loading the particles into the send buffers the size of the buffer is compared to the number of particles to load, if the buffer is not large enough then the buffer is reallocated having a larger size. The same check is made for the recv buffers before the MPI transfer is performed.
Before unloading the particles from the recv buffers into the arrays that contain the particle data, the new number of local particles (including the one received from the MPI transfer) is compared to the size of the particle data arrays, if the arrays are not large enough then new larger arrays for …

Extend the particles arrays and buffers for transfers as needed

---

src/system_tests/system_tester.cpp
src/system_tests/system_tester.h

Now the systemTest::SystemTestRunner class can be used to just launch cholla and then the user can do whatever analysis they want to determine correctness.

Add support for launch only system tests

---

Makefile
src/VL_3D_cuda.cu
src/boundary_conditions.cpp
src/boundary_conditions_cuda.cu
src/boundary_conditions_cuda.cuh
src/global_cuda.h
src/grid3D.cpp
src/grid3D.h
src/initial_conditions.cpp
src/io.cpp
src/main.cpp
src/mpi_boundaries.cpp
src/mpi_boundaries_cuda.cu
src/mpi_routines.cpp
src/mpi_routines.h
src/nvtx.h

This pull request adds the option (`DEVICE_COMM`) to perform inter-process halo exchange directly on the device. This option removes the need to: 
1. Copy data from device to host
2. Perform packing on the host
3. Run MPI send/receive routines to exchange data on the host
4. Perform unpacking on the host
5. Copy data from host to device
Instead, with this option, the routines are changed to:
1. Perform packing on the device
2. Run MPI send/receive routines to exchange data on the device, utilizing CUDA-aware-MPI
3. Perform unpacking on the device
For a workflow with the input shown [here](https://github.com/hummingtree/cholla/wiki):
- On a DGX-1V (with 8x NVIDIA V100 GPUs) the `DEVICE_COMM` version is **6x** faster, and
- On a DGX-A100-80GB (with 8x NVIDIA A100 GPUs) the `DEVICE_COMM` …

Add the option to perform inter-process halo exchange directly on the device

---

.github/workflows/build_tests.yml

There is some ubuntu or GitHub issue that is causing the MPI
installation to fail on the automated builds. The MPI installation
has been replaced with a MPI setup action written by the mpi4py group
which has a workaround for this issue.
Due to bugs in a previos version of ROCm the version used in the
GitHub Actions build was locked to v4.3.1. Those issues have long
sinced been resolved so now the HIP builds will use the latest
version of ROCm.

Fix MPI installation and ROCm on GitHub Actions

---

src/io/io.cpp
src/mpi/cuda_mpi_routines.cu
src/old_cholla/subgrid_routines_3D.cu

This PR confirms that I was wrong in the CAAR meeting -- currently the CAAR branch will not compile without MPI. 
I added two protections (and a soon-to-be-deprecated include to subgrid routines), and now (CAAR branch + hydro only) will work without MPI (MPI_CHOLLA off, MPI_GPU off, and compiler set to g++ instead of mpicc(x)). 
One outstanding but scientifically unimportant issue is that the "domain" attribute of HDF5 output differs for irrelevant dimensions (Y,Z for 1D, Z for 2D, no difference for 3D) between MPI and non-MPI. This is based on how the variables H.ydglobal and H.zdglobal are set.

Hydro without MPI

---

src/integrators/VL_3D_cuda.cu

The VL integrator FreeMemory call was freeing the grav_ppotenttial device array which is also freed by the Reset function causing a CUDA error at the end of the simulation.
Deleted redundant CudaFree from the VL integrator

Fixed duplicate CudaFree of grav_potential device array

---

src/gravity/gravity_boundaries.cpp
src/gravity/gravity_boundaries_gpu.cu
src/grid/boundary_conditions.cpp
src/grid/grid3D.h
src/particles/density_boundaries.cpp
src/particles/density_boundaries_gpu.cu

Implemented a periodic copy of the gravitational potential and particles density when using GRAVITY_GPU and one of the axes is handled by a single mpi task i.e. n_mpi=1 or n_mpi=2 or n_mpi=4.

Fixed GRAVITY_GPU periodic boundaries when n_mpi=1, 2, 4

---

builds/make.type.cooling
src/global/global_cuda.cu
src/global/global_cuda.h
src/grid/grid3D.cpp
src/hydro/hydro_cuda.cu
src/integrators/CTU_1D_cuda.cu
src/integrators/CTU_2D_cuda.cu
src/integrators/CTU_3D_cuda.cu
src/integrators/VL_1D_cuda.cu
src/integrators/VL_2D_cuda.cu
src/integrators/VL_3D_cuda.cu
src/integrators/simple_3D_cuda.cu
src/main.cpp

Passes All Tests
- Switched the first time step calculation to be done on GPU rather
than CPU
- Make the `host` and `device` `dti_array`'s local to `Calc_dt_GPU`
- Removed last reference to `HYDRO_GPU` flag in cooling make file
- Added comments to main to clarify what `Grid3D::set_dt` does
- Deleted CPU time step functions
- `calc_dti_cpu`
- `calc_dti_cpu_1D`
- `calc_dti_cpu_2D`
- `calc_dti_cpu_3D`
- `calc_dti_CPU_3D_function`

Move all timestep calculations to GPU

---

Makefile
builds/make.type.hydro
src/io/io.cpp
src/main.cpp
src/utils/timing_functions.cpp

The Git SHA and the list of compile time preprocessor macro flags (i.e. all the `-D` arguments) are now passed to Cholla in the `GIT_HASH` and `MACRO_FLAGS` macros. The values of them are then written out to: 
- terminal output
- run_output.log
- run_timing.log
- ASCII data output
- HDF5 data output
This should enable us to know exactly how Cholla was compiled to generate a given data set.

Make Cholla output the git SHA at which it was compiled and the macro flags it was compiled with

---

src/particles/particles_3D.cpp

Fix from Trey to prevent particles on MPI boundaries from being discarded and a second fix to keep particle IDs as int

fix particle id type mismatch and discarded boundary particles problem

---

builds/make.host.c3po
src/grid/cuda_boundaries.cu
src/grid/grid3D.h
src/grid/initial_conditions.cpp
src/hydro/hydro_cuda.cu
src/io/io.cpp
src/utils/mhd_utilities.h
src/utils/mhd_utilities_tests.cpp

Magnetic fields were stored on the "left" (i-1/2) face of the cell that was indexed; i.e. the i,j,k cell stored the magnetic fields at the i-1/2, j-1/2, and k-1/2 faces. This is opposite the way Cholla stores the other face centered quantities (interface states and fluxes) so I switched the magnetic fields to be stored on the "right" faces instead.
- Add `-g` compiler flag to `CXXFLAGS_OPTIMIZE` on C-3PO
- Fix bug in `Average_Cell_All_Fields` where it only rebuilt one magnetic field face in a cell instead of both
- Significantly simplified the code for output MHD ASCII files
- Removed code that could output the grid to an HDF5 file when less than 3 dimensions were present. No other part of the code supports non-3D MHD

Switch the cell side magnetic fields are stored

---

Makefile
src/utils/mhd_utilities_tests.cpp
src/utils/testing_utilities.cpp

The presense of the `-Ofast` flag, specifically the `--ffinite-math-only` flag that it calls, caused all calls to `std::isnan` and `std::isinf` to be undefined. In practice they always returned false which effectively broke the handling of Nans and infs in `testingUtilities::ulpsDistanceDbl`which in turn is call by all of our FP64 comparison utilities. This has been fixed by settting `BUILD = DEBUG` when building the tests.
Also, `testingUtilities::nearlyEqualDbl` has been refactored so that it always returns proper values of of `absoluteDiff` and `ulpsDiff`. Before it would only compute some of those values and then exit early if they were found to be passing. This could cause `ulpsDiff` to be undefined when comparing small numbers. Now both `absoluteDiff` and `ulpsDiff` are computed …

Fix bug caused by `-Ofast` in tests, refactor `nearlyEqualDbl`

---

src/cooling/cooling_cuda.cu
src/utils/cuda_utilities_tests.cpp
src/utils/hydro_utilities_tests.cpp

Change `HYDROSYSTEM` to just `HYDRO` in the naming of the hydro and cuda utility function unit test naming at Bob's request, as that naming scheme is reserved for system tests. Reran all hydro tests and they passed.

hydro and cuda utils unit test naming

---

src/global/global_cuda.cu
src/global/global_cuda.h
src/grid/grid3D.cpp
src/hydro/hydro_cuda.cu
src/utils/gpu.hpp
src/utils/reduction_utilities.cu
src/utils/reduction_utilities.h
src/utils/reduction_utilities_tests.cu

Cholla regularly performs reductions and previously they were done with a hybrid GPU/CPU approach that was complicated to implement. This commit introduces a reduction that can be performed with a single device function call at the end of a transform-reduce kernel and also a kernel that can be used to reduce an array. Currently the only reduction that is implemented is for finding the maximum, however, it would be very easy to implement it for any common reduction by replacing every instance of `fmax` with the appropriate operator. Tests for the reductions are included.
Note that any transform-reduce kernels that utilize this reduction should use a grid stride loop to perform as much of the tranform-reduce as possible. It's important to minimize the number of blocks as the performance is …

GPU Resident Reduction Tools

---

builds/setup.crc.gcc.sh
builds/setup.frontier.cce.sh
builds/setup.summit.gcc.sh
builds/setup.summit.xl.sh

At the request of @alwinm I set GoogleTest to automatically load during setup on CRC, Frontier/Crusher, and Summit. On other systems the GoogleTest module can be loaded manually or GoogleTest can be installed from source using the bash function in `run_tests.sh`

Set googletest to automatically load during setup

---

.github/workflows/build_tests.yml
builds/scripts/run_tests.sh

GoogleTest 1.12.1 is the last version to support C++11 so we need to fix the version we use at that until we update to C++14 or newer. The `run_tests.sh` script was updated to only download that version of GoogleTest and to only fetch that single commit since we don't need the whole commit history.
Bumped version of cuda-toolkit action from 0.2.4 to 0.2.8. Most salient change is that this automatically enables caching for faster installs. This improves the time to install the cuda-toolkit by 1-2 minutes.

Fix GoogleTest version & update cuda-toolkit action

---

src/hydro/hydro_cuda.cu
src/utils/cuda_utilities.h
src/utils/cuda_utilities_tests.cpp
src/utils/reduction_utilities.cu
src/utils/reduction_utilities.h

- Refactor reduction utilities to avoid a race condition. Previously the value to compare against was being set at the beginning of the  kernel or device function. This could lead to a race condition where the zeroeth thread was trying to initialize that value while an  already running thread was trying to atomically write to it. Now the  value in globabl memory is not set at all and instead must be set  elsewhere; the `cuda_utilities::setScalarDeviceMemory` templated  function has been added for that purpose.
- Replace calls to `reduction_utilities::gridReduceMax` in time step calculations with calls to `reduction_utilities::blockReduceMax` to  reflect what is actually being done
- Add a new `cuda_utilities::setScalarDeviceMemory` function for  setting device memory. This is basically an …

Fix race condition in GPU reductions

---

builds/make.host.github
builds/run_tests.sh

If `buildAndRunTests` is passed the `-g` flag it now clones and builds the latest version of GoogleTest instead of the latest version that is compatible with C++11. This is mostly relevant for the automated builds and anyone who wants to build GoogleTest from source since Crusher, Summit, Pitt CRC, and C-3PO all have older version of GoogleTest.
With the recent restructuring of branches I'm not sure where this PR should land. I've chosen main for now since I think we talked about CAAR being deprecated but please redirect it to the appropriate branch.

Update `run_tests.sh` to use GoogleTest main

---

.github/workflows/build_tests.yml
Makefile
builds/make.host.crc
builds/make.host.frontier
builds/make.host.github

The latest version of ROCm and hipFFT don't install in the same directory given by the ROCM_PATH environment variable. hipFFT always installs in /opt/rocm-5.2.0 and ROCm installs in the director for its version. If you try to install ROCm v5.2.0 and hipFFT then it errors out. The workaround for this is to use a HIPFFT_PATH variable for linking hipFFT on the GitHub Actions builds.
I've also refactored the Cholla Compile script to more neatly break up portions of the job, remove old code that's no longer used, and enable use to install specific versions of ROCm.
This commit should end up on dev and main to fix the builds for both branches. Adding the ROCm version as a matrix variable also changes the name of the checks required to merge. I'll take care of that change.
Other
- Update …

Workaround for HIPFFT issues on GitHub Actions

---

.github/workflows/build_tests.yml
Makefile

This removes the workaround from PR #175 and replaces it with the correct way to install hipFFT in a generalized manner. This commit should probably make it on to main but it isn't critical.
- Fix hipFFT + rocFFT install to install the version compatible with the version of ROCm being installed
- Removed Clang install since it's no longer required
- Remove hipfft path workaround in Makefile
- Organize ROCm install steps better

Fix GitHub Actions Builds

---

src/io/io.cpp

There was a "x" where it should have been a "z".
Resolves #180

Fix bug/typo in 1D IO routines

---

src/particles/density_CIC_gpu.cu
src/particles/gravity_CIC_gpu.cu
src/particles/particles_boundaries_gpu.cu
src/particles/particles_dynamics_gpu.cu

When n_local = 0 and ngrid = 0, CUDA crashes as a result of trying to call a kernel with 0 blocks. Usually in the code this is avoided by always adding +1 to the number of blocks, but in my opinion I think it's preferable to avoid adding an extra block, avoid the kernel call altogether, and make the logic a little more explicit for future readers of the code. 
Currently I am proposing the pushed changes, but in the interest of consistency I can re-do these changes in the old way, or re-do the old ways to match these changes. 
I'll ping @ojwg since we've talked about these crashes, and I'll ping @bvillasen to tap his particles expertise.  
One nice feature about this pull request is that pure-hydro examples will now run with zero particles, even if particle flags were included.

Fix crashes when there are zero local particles

---

Makefile

Previously `make clobber` deleted any executable that matched the pattern `cholla*` in the entire repo. Now it only deletes executables that follow this pattern and are in `bin`. The reason is that I accidentally deleted an executable script who's name started with `cholla` and that seems like something that others will do as well

`make clobber` to only delete in `bin/`

---

builds/make.host.crc

This accidentally got changed in dev because of my cloudy table PR. In the future I'll submit separate PRs for main/dev to help avoid weird merging situations.

Fix make.host.crc to use c++17 again

---

.github/workflows/build_tests.yml

I set up this pull request by cherry-picking the dev commit, so down the road if/when dev gets merged into main, this won't generate a merge conflict!
I set up the build script to look for the docker containers: 
docker://alwinm/cholla:hip_github
docker://alwinm/cholla:cuda_github
When we create new versions, we can give them tags with other names, and then alias the tagname to hip_github and cuda_github. This way, we can update the Docker container while keeping a version history and easily being able to switch back to previous versions if necessary, all without requiring pull requests on github. 
I can set maintainers as collaborators on the Docker Hub repo so any of us can push images! 
Example:
Setting the github container version to 0.0, assuming you've already pushed 0.0.
```
docker …
```

new build-tests.yml for Docker container

---

src/system_tests/input_files/tHYDROSYSTEMSodShockTubeParameterizedMpi_CorrectInputExpectCorrectOutput.txt
src/system_tests/input_files/tMHDSYSTEMSodShockTubeParameterizedMpi_CorrectInputExpectCorrectOutput.txt

The Y and Z boundaries in the sod test were using the default boundaries. This will make them use transmissive boundaries, same as X does.

Fix sod tests boundaries

---

examples/3D/Dai_and_Woodward.txt
examples/3D/Ryu_and_Jones_2a.txt
examples/3D/Ryu_and_Jones_4d.txt
src/grid/cuda_boundaries.cu
src/grid/grid_enum.h
src/integrators/VL_3D_cuda.cu
src/mhd/ct_electric_fields.cu
src/mhd/ct_electric_fields.h
src/mhd/ct_electric_fields_tests.cu
src/mhd/magnetic_update.cu
src/mhd/magnetic_update_tests.cu
src/riemann_solvers/hlld_cuda.cu
src/riemann_solvers/hlld_cuda.h
src/riemann_solvers/hlld_cuda_tests.cu
src/system_tests/hydro_system_tests.cpp
src/utils/timing_functions.h

Since MHD needs a larger stencil the diode in the outflow BC's was causing issues. After discussion with @evaneschneider the diode has been disabled for MHD builds.
Minor tweaks to fix clang-tidy's `readability-qualified-auto` and `clang-analyzer-optin.cplusplus.UninitializedObject` checks.
The readablity check was fixed by commenting out some currently used code, it's not deleted since it will be used again when MHD is finished; at which time the actual error will be fixed.
The clang-analyzer check was fixed by initializing some member variables in the OneTime class. @alwinm, I'd like you to take a look at this and make sure I haven't broken anything.
- Switched more indexing over to using grid_enums and added enums for the CT electric fields.
- Cleaned up the arguments for the HLLD …

Remove outflow boundary condition diode for MHD

---

src/mpi/mpi_routines.cpp
src/mpi/mpi_routines.h

This restores the `MPI_Comm_node` function removed in PR #259 and which caused issue #266. While the return of that function was unused it did play an important roll in arranging MPI ranks for Cholla. This PR restores a refactored version of the function that is a bit simpler with the unused bit cut out.
Shout out to @helenarichie for finding the bug and @evaneschneider for identifying what needed to be fixed.
closes #266

Restore & refactor `MPI_Comm_node` function

---

python_scripts/cat_dset_3D.py
src/global/global.h
src/grid/initial_conditions.cpp
src/io/io.cpp
src/io/io.h
src/io/io_gpu.cu
src/io/io_tests.cpp
src/system_tests/cooling_system_tests.cpp
src/system_tests/hydro_system_tests.cpp
src/system_tests/input_files/tHYDROtMHDReadGridHdf5_RestartSlowWaveExpectCorrectOutput.txt
src/system_tests/system_tester.cpp

Added a test for MHD and hydro restarts. It doesn't work with gravity, particles, etc but would be pretty easy to extend to those or write new tests for them based off of this test.
The MHD I/O was outputting an extra cell in every direction when it should only output an extra cell in the direction of the magnetic field; i.e. the Bx dataset should be (nx+1, ny, nz) not (nx+1, ny+1, nz+1). This should fix that issue and clean up MHD I/O a bit in general.

Fix MHD I/O & Add Restart Test

---

src/grid/cuda_boundaries.cu
src/integrators/VL_1D_cuda.cu
src/integrators/VL_2D_cuda.cu
src/integrators/simple_1D_cuda.cu
src/integrators/simple_2D_cuda.cu
src/io/io.cpp

The MHD builds have been throwing some "unused variable" and "format overflow" warnings pretty much since the start. I finally got too annoyed with them and set out to fix them. 
I fixed most of the "unused variable" warnings by using an [attribute specifier](https://en.cppreference.com/w/cpp/language/attributes), which are new in C++17. You just add `[[maybe_unused]]` to the declaration of a variable if it might be unused. 
One of the "unused variable" warnings was actually an unused variable so I removed it and refactored a bit to use some of the cuda_utilities functions we've written. I'd like @helenarichie to take a look at commit c8a828f to make sure I didn't break anything.
The "format overflow" errors were fixed by replacing `char[]` arrays with `std::string`.

Fix compiler warnings in MHD build

---

Makefile
src/chemistry_gpu/chemistry_functions.cpp
src/io/io_tests.cpp
src/riemann_solvers/hlld_cuda.cu
src/system_tests/system_tester.cpp
src/system_tests/system_tester.h

This is a handful of small tweaks and fixes I've been putting off while I worked on debugging MHD. Most are minor but I would like @evaneschneider or @bvillasen to take a look at my change to the grid temperature function. I think there might be other places that should be using MHD energy in computations but I don't know where
- Have `make tidy` print out where the results are stored. This isn't obvious so now it tells you
- Replace straight sum in `systemTest::SystemTestRunner::runL1ErrorTest` with a Kahan sum to avoid loss of precision.
- Fix a minor bug in hydro restart test
- Replace file manipulation methods in `systemTest::SystemTestRunner` with `std::filesystem` calls

Miscellaneous Post MHD Tweaks/Fixes

---

.clang-tidy
builds/run_tests.sh
examples/3D/advecting_field_loop.txt
src/global/global.cpp
src/global/global.h
src/grid/grid3D.cpp
src/grid/grid3D.h
src/grid/initial_conditions.cpp
src/system_tests/input_files/tMHDSYSTEMParameterizedMpi_AdvectingFieldLoopCorrectInputExpectCorrectOutput.txt
src/system_tests/mhd_system_tests.cpp
src/system_tests/system_tester.cpp
src/utils/mhd_utilities.cu
src/utils/mhd_utilities.h
src/utils/mhd_utilities_tests.cu

- Example parameter file in `examples/3D/advecting_field_loop.txt`
- New parameter "R" for the radius of the field loop
- New initial conditions type `Advecting_Field_Loop` and an initializing function of the same name
- New MHD system test for the advecting field loop
- New function for initializing the magnetic field from the vector potential and a test to go with it
- Update `Grid3D::AllocateMemory` to use `grid_enums`
- Fix a typo in the `.clang-tidy` file
Fixes #280

Add Advecting Field Loop test & initial conditions

---

src/chemistry_gpu/chemistry_functions.cpp

Fix missing headers in `chemistry_functions.cpp`

---

examples/3D/advecting_field_loop.txt
examples/3D/mhd_blast.txt
src/global/global.cpp
src/global/global.h
src/grid/grid3D.h
src/grid/initial_conditions.cpp
src/system_tests/input_files/tMHDSYSTEMParameterizedMpi_AdvectingFieldLoopCorrectInputExpectCorrectOutput.txt
src/system_tests/input_files/tMHDSYSTEMParameterizedMpi_MhdBlastWaveCorrectInputExpectCorrectOutput.txt
src/system_tests/mhd_system_tests.cpp
src/utils/error_handling.cpp

- Example parameter file in examples/3D/mhd_blast.txt
- New parameter `P_blast` parameter to indicate the pressure in the over pressure zone of the blast
- New initial conditions type `MHD_Spherical_Blast` and an initializing function of the same name
- New MHD system test for the MHD blast wave
- New check in `Check_Configuration` to check that gamma is greater than one. I accidentally forgot to set gamma when setting up this test originally so I added a check to make sure that doesn't happen again.

Add MHD blast wave test & initial conditions

---

python_scripts/cat.py

Slightly upgraded version of cat scripts. 
Uses chunking for hydro output which makes concatenation much faster. 
Uses double-precision by default to avoid precision conversion bugs. 
Doesn't require as many input arguments as existing scripts, and is more explicit about which arguments are needed.

add cat.py to python_scripts

---

.gitignore
python_scripts/cat_dset_3D.py

The cat_dset_3D.py script required manual changes to use it. This made it impossible to use in an automated way and tricky to use manually. To address this it needed both a CLI interface and a python interface for calling from within another python script. Both have been added by moving all the concatenation code into the `concat_3d` function which handles the python interface and the new `main` function handles the CLI interface then calls `concat_3d`.
Also adds __pycache__ to the `.gitignore` along with some formatting to remove unnecessary newlines.

Refactor `cat_dset_3D.py` to provide an interface

---

src/reconstruction/plmc_cuda.cu
src/reconstruction/plmc_cuda.h
src/reconstruction/plmc_cuda_tests.cu
src/reconstruction/ppmc_cuda.cu
src/reconstruction/ppmc_cuda.h
src/reconstruction/reconstruction.h
src/reconstruction/reconstruction_tests.cu

I realized that I was recomputing the eigenvalues for the characteristic projections multiple times for no reason in the PPMC and PLMC reconstruction kernels. This refactor changes it so that the eigenvectors are only computed once and then used in all the projections. Overall this resulted in noticeable performance increases on both a V100 system (C-3PO) and on Frontier. The performance numbers are in this table, all times given are for the entire timestep, not just the PPMC kernel. The test was the Brio & Wu shock tube at 256^3 run with PPMC.
| Test                         | Time (ms/time step) | Registers (scalar/vector on AMD) |
|------------------------------|--------------------:|---------------------------------:|
| C-3PO Initial                |               189.1 | …

Optimize Characteristic Computations in Refactored Reconstructors

---

src/utils/error_handling.cpp

This changes the message that the boundary conditions check outputs to make it more useful.

Update boundary condition check message

---

.gitignore
Makefile
builds/run_tests.sh

The run_tests.sh script now has the ability to generate a coverage report for the CPU code. It can be generated by passing the -l flag to the buildAndRunTests function then the coverage report will be available in the generated HTML website in
bin/html_coverage_report_${CHOLLA_MAKE_TYPE}
The reason that this isn't being added to the CI pipeline is that there's no way to generate a coverage report of GPU code and that substantially limits the usefulness of a coverage report for us. If that changes in the future then having coverage information could be useful.

Add the ability to generate test coverage reports

---

src/utils/error_handling.cpp

1. There were `or` statements when it should have been `and` in the `Check_Configuration` function.
2. `Check_Configuration` was only checking that the VL integrator was used and the SIMPLE integrator wasn't in MHD builds. Expanded that check to make sure the CTU integrator isn't being used either.

Fix MHD Configuration checks

---

src/main.cpp
src/mpi/mpi_routines.cpp
src/mpi/mpi_routines.h
src/utils/cuda_utilities.cpp
src/utils/cuda_utilities.h
src/utils/gpu.hpp

When `CPU_TIME` is enabled Cholla now prints out how much GPU memory is allocated at the end of each time step. To do this I added new functions, `Reduce_size_t_Max` an `Print_GPU_Memory_Usage`, to determine the maximum amount of memory used on any GPU and print that information out. The motivation was to determine how many cells we can fit on a given GPU with a given Cholla configuration easily. Early tests show that on Frontier we can fit about 457^3 cells per GPU in an MHD only build.

Print out the amount of GPU memory used at the end of each time step

---

src/mhd/ct_electric_fields_tests.cu

I only test the states that are actually used in the kernel.
Also, I tried refactoring all the constant parameters as template parameters to see if that helped performance. It had no impact.

Add a test for the `_ctSlope` function

---

.clang-tidy
src/utils/error_handling.cpp
src/utils/timing_functions.cpp

- Allow MHD to build with the `OUTPUT` and `HDF5` flags absent
- Permit single line if statements without braces in clang-tidy
- Minor refactor of the `Time::Print_Average_Times` to make future changes to the header easier
- Add a note about the reduced range of the timers to `run_timing.log`

Misc. Small Changes for MHD timing

---

.clang-tidy

I accidentally committed a test setup that I use that disabled almost all checks. This PR fixes it. Once this is merged then all PRs should be updated and rerun through the CI pipeline to make sure nothing was missed.

Fix clang-tidy config error that disabled almost all checks

---

src/global/global.cpp
src/global/global.h
src/io/io.cpp

Now you can output slices of the grid when MHD is turned on.

Add MHD Support to Slice Outputs

---

tools/cholla-nv-compute-sanitizer.sh
tools/clang-format_runner.sh
tools/clang-tidy_runner.sh

`tools/clang-tidy_runner.sh` will run clang-tidy on all builds in parallel.
Other scripts in the tools directory got an updated method of determining the cholla directory that works if invoked from outside the directory.

Add script to run clang-tidy on all builds

---

src/grid/grid3D.cpp
src/main.cpp
src/utils/gpu.hpp
src/utils/timing_functions.cpp
src/utils/timing_functions.h

Added a section to `OneTime::end()` that checks if the rank took more than 10% longer than average. If it did then it prints the node ID and GPU PCIe Bus ID to std::cerr. This is not enabled for all timers by default and enabling it requires passing the proper argument to `OneTime::end()`; it's currently enabled only for the `Hydro_Integrator` timer
This should let us figure out if the weird performance issues on Frontier are Cholla or a small number of slow GPUs.
If a maximum number of timesteps was set with `N_STEPS_LIMIT` then the final time step would still output even if the `OUTPUT` macro was not provided. Added ifdef statement to fix this.

Method to Identify Slow GPUs + Output bugfix

---

src/dust/dust_cuda.cu
src/io/io.cpp
src/utils/hydro_utilities.h
src/utils/hydro_utilities_tests.cpp

Per the discussion in PR #365 I've added MHD support to the projection and rotated projection outputs along with a minor refactor to those functions to accomplish this and utilize more of the utility functions we've written.
I also added a utility function for computing the temperature from the conserved variables (`hydro_utilities::Calc_Temp_Conserved`). Internally it simply calls `hydro_utilities::Calc_Pressure_Conserved` and `hydro_utilities::Calc_Temp` to compute the temperature.
`Dust_Kernel` had few DE related bugs in it that I fixed with help from @helenarichie. While doing that I also slightly redefined `hydro_utilities::Calc_Temp_DE` to take the total gas energy instead of the specific gas energy and density.

Add MHD Support to Projection and Rotated Projection Outputs

---

src/integrators/VL_3D_cuda.cu
src/utils/cuda_utilities.h

I applied `AutomaticLaunchParams` to all the kernels called in the VL_3D integrator. Ended up with a 10-15% improvement in performance on MHD with both a V100 and MI250X. I can apply it to other places or time consuming kernels if anyone wants me to.
[v100_run_timing.log](https://github.com/cholla-hydro/cholla/files/13665997/v100_run_timing.log)
[frontier_run_timing.log](https://github.com/cholla-hydro/cholla/files/13665998/frontier_run_timing.log)
Resolves #232
Removed density and temperature floors from default MHD builds
Updated some comments to be inline with current code.

Set launch parameters of some high cost kernels automatically
